# Generated by Django 6.0.2 on 2026-02-09 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('users', '0002_membershiptier_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.membership'),
        ),
    ]
