# Generated by Django 6.0.2 on 2026-02-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membershiptier_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_class',
            field=models.IntegerField(blank=True, help_text='Class 1-12', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='school_college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sports_discipline',
            field=models.CharField(choices=[('Badminton', 'Badminton'), ('Volleyball', 'Volleyball'), ('Basketball', 'Basketball'), ('Table Tennis', 'Table Tennis'), ('Others', 'Others')], default='Others', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='student_ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(blank=True, choices=[('school', 'School Student'), ('college', 'College Student')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
