# Generated by Django 6.0.2 on 2026-02-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_course_end_date_user_course_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, help_text='User is banned until this date.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_permanently_banned',
            field=models.BooleanField(default=False, help_text='User is permanently banned.'),
        ),
    ]
