# Generated by Django 6.0.2 on 2026-02-13 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(help_text='Reason for closure', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, help_text='Leave blank to close ALL facilities', null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'facility')},
            },
        ),
    ]
