# Generated by Django 6.0.2 on 2026-02-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facilityclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='capacity_per_slot',
            field=models.IntegerField(default=1, help_text='Number of bookings allowed per slot'),
        ),
    ]
