# Generated by Django 6.0.2 on 2026-02-13 03:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_facility_capacity_per_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'facility', 'slot', 'booking_date')},
        ),
    ]
