# Generated by Django 6.0.6 on 2026-06-07 08:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilityclosure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='facilityclosure',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='Leave blank to close whole day', null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.timeslot'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='facility_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterUniqueTogether(
            name='facilityclosure',
            unique_together={('date', 'facility', 'slot')},
        ),
    ]
